name: Docker

on:
  release:
    types:
      - created
  push:
    paths-ignore:
      - "*.md"
      - ".github/**"
      - "!.github/workflows/nightly.yml"
    branches:
      - main
env:
  CONTAINER_NAMESPACE: ghcr.io/${{ github.repository_owner }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: VERSION=nightly
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CONTAINER_NAMESPACE }}/pg-replicator:nightly

      - name: Build (release)
        uses: docker/build-push-action@v6
        if: github.event_name == 'release'
        with:
          context: .
          build-args: VERSION=${{ github.event.release.name }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.CONTAINER_NAMESPACE }}/pg-replicator:${{ github.event.release.name }},${{ env.CONTAINER_NAMESPACE }}/pg-replicator:latest
